### ISSUE TITLE
Is tsps dormant or discontinued?

### ISSUE THREAD

**Issue by l2dy** [cooldavid/tsps#2]

**Comment by cooldavid** [comment]
Three questions:
1. Found any bug?
2. Want any feature?
3. Anyone still using it?

**Comment by l2dy** [comment]
1. Not about bugs.
2. Updated README.
3. This is the only TSP Server implementation I've found.

It's been years since the last commit so I'm not considering it on-going. I'm just asking for a new README stating the status of the project.

**Comment by cooldavid** [comment]
Ahh... OK... I'll update the README. :smile: 
It's nice to know someone still using it.
